### ISSUE TITLE
[EL-PRO]基本設計-画面レイアウト仕様書

### ISSUE THREAD

**Issue by IotaTech-Info** [ebforlearng1java/EBPro_G2#51]
## テンプレート
[画面レイアウト仕様書_テンプレート.xlsx](https://github.com/ebforlearng1java/EBPro_G2/files/8423882/_.xlsx)

**Comment by OliveSya** [comment]
[ブック.xlsx](https://github.com/ebforlearng1java/EBPro_G2/files/8438814/default.xlsx)
